[package]
name = "matryx_generator"
version = "0.1.0"
edition = "2018"

[dependencies]
led_matrix_zmq = { git = "https://github.com/Knifa/led_matrix_zmq.git" }
# led_matrix_zmq = { path = "../led_matrix_zmq" }

palette = "0.6.0"
rand = "0.8.4"
embedded-graphics = "0.7.1"
chrono = "0.4.24"
u8g2-fonts = { version = "0.2.0", features = ["embedded_graphics_textstyle"] }